### ISSUE TITLE
Please rewrite this spec

### ISSUE THREAD

**Issue by AkaKuro4Ever** [learn-co-curriculum/rails-amusement-park#11]
Hello. This lab's spec is extremely confusing in many ways and was extremely frustrating. 

1. The line ' # user_signup method is defined in login_helper.rb' in users_features_spec.rb is misleading and leads one to think they need to create a user_signup & user_login method and a module called login_helper
2. The specifics about how mood translates from a number to a word is required to pass the first test, but isn't mentioned until maybe the 3rd spec.
3. Requirements on what actual pages are needed or controllers are not at all specified. While I understand that they are needed, since there is no spec for them, I don't know what the tests are expecting. Views are not specified at ALL. These specs do not flow in a way for people who don't know what the entire lab is supposed to be and are coding along with the tests.
4. The requirement that the index page and the users/new page be linked to users#new route is very confusing
I'm still on the first spec test, so I apologize if this issue is too early to write. I spent the last 3 hours working on the first issue with 2 learn experts for more than half this time. Thanks for your time!

**Comment by cjbrock** [comment]
Hi @AkaKuro4Ever! Thank you for your feedback. We're currently in the middle of a big project to rework the Rails section, and we will absolutely take your feedback into account. We hear student frustration around this lab regularly and will definitely work to make the spec for this lab more clear. Thank you for taking your time to enumerate your struggle - this will help us to focus on exactly what we need to make better.
// Corinna
