### ISSUE TITLE
Tests and solution branch not aligned

### ISSUE THREAD

**Issue by justinddaniel** [learn-co-curriculum/rails-amusement-park#12]
The tests shown in spec for the solution branch do not align with the the current tests in the master branch students receive.

**Comment by cjbrock** [comment]
Hi @justinddaniel! Thank you for letting us know that the branches are out of sync. We will work on bringing them back in sync. I've created a new issue that you can track [here](https://github.com/learn-co-curriculum/rails-amusement-park/issues/14). 
// <3 Corinna
