### ISSUE TITLE
Grammar Issue on Line 251 of Test Cases

### ISSUE THREAD

**Issue by OkayAtay** [learn-co-curriculum/rails-amusement-park#13]
The line reads

    expect(page).to have_content("You do not have enough tickets the #{@ferriswheel.name}")
    expect(page).to have_content("Tickets: 1")

I assume it should read "You do not have enough tickets..to ride...

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
