### ISSUE TITLE
Potential Turbolinks/Sass conflict causing test failure

### ISSUE THREAD

**Issue by Lindsay-c-Dennis** [learn-co-curriculum/rails-amusement-park#15]
Technical coach feedback:

A student working on this lab was repeatedly running into this error: 

`Failure/Error: <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
      
      ActionView::Template::Error:
        Invalid CSS after "...top: 4px solid ": expected ";", was "\	;"
      # (sass):4014
`
This error was replicated on my machine, and when I cloned down another student's lab who had recently made a pull request, I got the same error. We were able to get rid of the error by commenting out the these two lines in the application.html.erb layout: 

`  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>`

**Comment by drakeltheryuujin** [comment]
Hi there,

I'm having difficulty reproducing the issue, so I'm going to close it for now.

If you can provide further detail about the steps required to reproduce the issue and any additional relevant information about your development environment (local or IDE), I'd be happy to take a second look!

As always, thanks for contributing! 💙
