### ISSUE TITLE
run bundle update

### ISSUE THREAD

**Issue by ghost** [learn-co-curriculum/rails-amusement-park#16]
for this error ` # --- Caused by: ---
     # Sass::SyntaxError:
     #   Invalid CSS after "...top: 4px solid ": expected ";", was "\   ;"
     #   (sass):4014`

run `bundle update`, and it will update the sass gem from 3.7.0 to 3.7.2, which should resolve this error

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.
We have updated the materials and believe your issue to have been resolved.
If you do not believe that this issue has been addressed, please re-open this issue. 💙
