### ISSUE TITLE
The factory_girl gem is deprecated. Please upgrade to factory_bot

### ISSUE THREAD

**Issue by ICanDoAllThingThroughChrist** [learn-co-curriculum/rails-amusement-park#19]
after issuing command "bundle install" with factory_bot_rails in gemfile, the console just spins and gemfile.lock failed to create

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.
We have updated the materials and believe your issue to have been resolved.
If you do not believe that this issue has been addressed, please re-open this issue. 💙
