### ISSUE TITLE
Capybara Error "Unable to find visible field 'password' that is not disabled"

### ISSUE THREAD

**Issue by chienleow** [learn-co-curriculum/rails-amusement-park#26]
Please go to line 15 in `login_helper.rb`, it should be `fill_in("user_password", :with => "password")` instead of `fill_in("password", :with => "password")`, appreciate someone fixing it, thank you!

**Comment by lizbur10** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved. 
Note, however, that if you are working in Canvas the changes may not show up 
right away.

We apologize for any frustration you might have encountered during this process
but thank you for helping us ensure that those who follow in your path will not
encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this
issue. 💙

**Comment by ChristopherBlack22** [comment]
This issue is still ongoing

**Comment by lizbur10** [comment]
Hi @ChristopherBlack22  - sorry to hear that! Can you provide more detail about the error(s) you're getting?
