### ISSUE TITLE
spec/support/login_helper.rb method admin_login

### ISSUE THREAD

**Issue by ismayton** [learn-co-curriculum/rails-amusement-park#28]
Method to log in a registered admin user looks for wrong password field, line 28

Existing: fill_in("password"), :with => "password")

Edit: fill_in("user_password", :with => "password")

This method should look for the same field that method user_login looks for (on line 21)

**Comment by lizbur10** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved. 
Note, however, that if you are working in Canvas the changes may not show up 
right away.

We apologize for any frustration you might have encountered during this process
but thank you for helping us ensure that those who follow in your path will not
encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this
issue. 💙
