### ISSUE TITLE
Thank you for spotting this issue and providing feedback.

### ISSUE THREAD

**Issue by ChristopherBlack22** [learn-co-curriculum/rails-amusement-park#32]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved. 
Note, however, that if you are working in Canvas the changes may not show up 
right away.

We apologize for any frustration you might have encountered during this process
but thank you for helping us ensure that those who follow in your path will not
encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this
issue. 💙

_Originally posted by @lizbur10 in https://github.com/learn-co-curriculum/rails-amusement-park/issues/26#issuecomment-760975708_

**Comment by ChristopherBlack22** [comment]
This issue appears to still exist

**Comment by lizbur10** [comment]
Hi @ChristopherBlack22 ! I'm sorry to hear that! Can you provide more detail about the error you're getting?

Thanks!

**Comment by lizbur10** [comment]
Hi @ChristopherBlack22 ! I'm going to go ahead and close this issue. If you're able to provide any additional details please feel free to re-open it.

Thanks for contributing to the Flatiron School curriculum! 💙
