### ISSUE TITLE
Re-do this github directory

### ISSUE THREAD

**Issue by kostanzhoglo** [learn-co-curriculum/rails-amusement-park#4]
Hi,

The solution code is the one that is the default fork and clone.
I'll erase mine and start from scratch, but when I ran $ learn in my terminal, I started off by passing all 63 tests.

I'm sure it was just a mistake from the roll-out of version 5 of the curriculum today.
Thanks,
Jeff

**Comment by hansenjl** [comment]
The solution version was mistakenly included in the new Rails Amusement Park repo

@weezwo

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.
We've removed the solution from the master branch.
Thanks 💙
