### ISSUE TITLE
just got the completed lab when I used learn open

### ISSUE THREAD

**Issue by josh-kramer-dev** [learn-co-curriculum/rails-amusement-park#5]
went to open this lab via the learn open command, and when the files opened up in my text editor, they looked like they were all done. ran learn, and all 62 tests came back passed. looks like it may have had the solution branch merged into the master branch last week because the master branch has 'all tests passing' as the commit messages for the file folders. 

Can it be reset so I can do this lab?

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.
We've removed the solution from the master branch.
Thanks 💙
