### ISSUE TITLE
Marked incomplete despite completing this lab 3 months ago

### ISSUE THREAD

**Issue by bkhartmire** [learn-co-curriculum/rails-amusement-park#6]
Suddenly this lab is marked as incomplete, but I completed it several months ago. So Learn thinks I'm 'currently working on' this lab even though I'm already several units ahead. I've tried resubmitting the lab in order to 'complete' it but because it appears the same as the lesson's (because I think there's an issue with the solution being included), it will not let me push my version up to Github.

**Comment by drakeltheryuujin** [comment]
Hi there! This request sounds like an improvement to the Learn platform. [Raising issues on GitHub](http://help.learn.co/improving-learn/contributing-to-lessons/raising-an-issue-with-a-lab-or-lesson) should be reserved for problems with the curriculum itself (doesn't work, throws a Ruby error, etc.)

If Learn is misbehaving, please direct your bug report to bugs@learn.co.

If, on the other hand, we've misunderstood the purpose of this request, please
re-open this issue, provide any additional information you can, and we will try to discern a proper path to resolution.
