### ISSUE TITLE
Solution in the master branch?

### ISSUE THREAD

**Issue by thelittlestschnauzer** [learn-co-curriculum/rails-amusement-park#7]
I cloned from github and it appears the master branch is the solution. I ran tests and they all passed without me having to solve anything. Is there anyway for this to be changed and then I can complete the lab? Thanks!

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.
We have updated the materials and believe your issue to have been resolved.
Thanks 💙
