### ISSUE TITLE
Lab completed but will not show as finished.

### ISSUE THREAD

**Issue by hong-werdna** [learn-co-curriculum/rails-amusement-park#9]
Similar issue to Model Class Methods lab. Lab completed but will not update progress meter in track as well as the curriculum tab. Please advise.

**Comment by drakeltheryuujin** [comment]
Hi there! This request sounds like an improvement to the Learn platform. [Raising issues on GitHub](http://help.learn.co/improving-learn/contributing-to-lessons/raising-an-issue-with-a-lab-or-lesson) should be reserved for problems with the curriculum itself (doesn't work, throws a Ruby error, etc.)

If Learn is misbehaving, please direct your bug report to bugs@learn.co.

If, on the other hand, we've misunderstood the purpose of this request, please
re-open this issue, provide any additional information you can, and we will try to discern a proper path to resolution.
